### ISSUE TITLE
index.htm build/bundle.js not exist

### ISSUE THREAD

**Issue by polygontwist** [robz/Linkages3#7]
index.htm build/bundle.js not exist i can not run this. npm run-script build not work.

> D:\javascript\Linkages3-master>npm run-script build

> @0.0.1 build D:\javascript\Linkages3-master
> mkdir build 2> /dev/null; browserify src/main.js -t babelify | uglifyjs -am > build/bundle.js
> 
> Das System kann den angegebenen Pfad nicht finden.
> 
> npm ERR! Windows_NT 10.0.14393
> 
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
> npm ERR! node v7.2.1
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! @0.0.1 build: `mkdir build 2> /dev/null; browserify src/main.js -t babelify | uglifyjs -am > build/bundle.js`
> npm ERR! Exit status 255
> npm ERR!
> npm ERR! Failed at the @0.0.1 build script 'mkdir build 2> /dev/null; browserify src/main.js -t babelify | uglifyjs -am > build/bundle.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the  package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     mkdir build 2> /dev/null; browserify src/main.js -t babelify | uglifyjs -am > build/bundle.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls
> npm ERR! There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\javascript\Linkages3-master\npm-debug.log

can you please add the bundle.js?

**Comment by robz** [comment]
@polygontwist thanks for report. The message you received:

> npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Suggests that you might not have run run `npm install` first. Can you try that?

If it still doesn't work, try editing line 9 of package.json to:

  
    "build": "browserify src/main.js -t babelify | uglifyjs -am > build/bundle.js",

And then run `mkdir build` first before running `npm run-script build`. 

Let me know if either of these work for you!

**Comment by polygontwist** [comment]
no, i have npm install -global for other Projekts.

ok, my 2. test: 
-I have npm and node.js updated to the current version
-npm install -g graceful-fs graceful-fs  (4.1.11)
-npm install --global --production windows-build-tools
i have installed phython (on message requred this?) 

-i chage the package.json
-i added  `build` directory
-`npm install `give:


> D:\javascript\Linkages3-master>npm install
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> 
> > contextify@0.1.15 install D:\javascript\Linkages3-master\node_modules\contextify
> > node-gyp rebuild
> 
> 
> D:\javascript\Linkages3-master\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\andreas\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
>   contextify.cc
>   win_delay_load_hook.cc
> ..\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate' [D:\javascri
> pt\Linkages3-master\node_modules\contextify\build\contextify.vcxproj]
>   c:\users\andreas\.node-gyp\7.2.1\include\node\v8.h(4696): note: see declaration of 'v8::ObjectTemplate'
> ..\src\contextify.cc(131): warning C4996: 'v8::Function::NewInstance': was declared deprecated [D:\javascript\Linkages3
> -master\node_modules\contextify\build\contextify.vcxproj]
>   c:\users\andreas\.node-gyp\7.2.1\include\node\v8.h(3292): note: see declaration of 'v8::Function::NewInstance'
> ..\src\contextify.cc(182): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [D:\javascript\Li
> nkages3-master\node_modules\contextify\build\contextify.vcxproj]
>   c:\users\andreas\.node-gyp\7.2.1\include\node\v8.h(2949): note: see declaration of 'v8::Object::GetRealNamedProperty'
> ..\src\contextify.cc(209): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [D:\javascript\Li
> nkages3-master\node_modules\contextify\build\contextify.vcxproj]
>   c:\users\andreas\.node-gyp\7.2.1\include\node\v8.h(2949): note: see declaration of 'v8::Object::GetRealNamedProperty'
> ..\src\contextify.cc(210): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [D:\javascript\Li
> nkages3-master\node_modules\contextify\build\contextify.vcxproj]
>   c:\users\andreas\.node-gyp\7.2.1\include\node\v8.h(2949): note: see declaration of 'v8::Object::GetRealNamedProperty'
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\andreas\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
> gyp ERR! System Windows_NT 10.0.14393
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andreas\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\javascript\Linkages3-master\node_modules\contextify
> gyp ERR! node -v v7.2.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> @0.0.1 D:\javascript\Linkages3-master
> `-- (empty)
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~0.3.1 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN @0.0.1 No repository field.
> npm WARN @0.0.1 No license field.
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andreas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v7.2.1
> npm ERR! npm  v4.1.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the contextify package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs contextify
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls contextify
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\javascript\Linkages3-master\npm-debug.log


Can I embed the source files differently into the index.html? Without build?
