### ISSUE TITLE
the URL is unreachable

### ISSUE THREAD

**Issue by WSPeng** [robz/Linkages3#8]
Hi! robz,

This is an amazing project, but I can't visit the url.

**Comment by robz** [comment]
Thanks @WSPeng ! Do you mean the tinyurl.com one? In that case, here's the full URL:

http://robz.github.io/linkage/?%7B%22points%22%3A%7B%22p0%22%3A%7B%22p1%22%3A%7B%22len%22%3A1%7D%2C%22p3%22%3A%7B%22len%22%3A14.49257629271213%7D%2C%22p4%22%3A%7B%22len%22%3A16.880617054368173%7D%2C%22p5%22%3A%7B%22len%22%3A7.877807259570914%7D%7D%2C%22p1%22%3A%7B%22p0%22%3A%7B%22len%22%3A1%7D%2C%22p2%22%3A%7B%22len%22%3A4.919773066101953%7D%7D%2C%22p2%22%3A%7B%22p1%22%3A%7B%22len%22%3A4.919773066101953%7D%2C%22p3%22%3A%7B%22len%22%3A14.39265093701525%7D%2C%22p5%22%3A%7B%22len%22%3A13.870998062666647%7D%7D%2C%22p3%22%3A%7B%22p0%22%3A%7B%22len%22%3A14.49257629271213%7D%2C%22p2%22%3A%7B%22len%22%3A14.39265093701525%7D%2C%22p4%22%3A%7B%22len%22%3A22.863240340909435%7D%7D%2C%22p4%22%3A%7B%22p0%22%3A%7B%22len%22%3A16.880617054368173%7D%2C%22p3%22%3A%7B%22len%22%3A22.863240340909435%7D%2C%22p6%22%3A%7B%22len%22%3A14.977745733903651%7D%7D%2C%22p5%22%3A%7B%22p0%22%3A%7B%22len%22%3A7.877807259570914%7D%2C%22p2%22%3A%7B%22len%22%3A13.870998062666647%7D%2C%22p6%22%3A%7B%22len%22%3A10.959615027924276%7D%2C%22p7%22%3A%7B%22len%22%3A11.251003326579944%7D%7D%2C%22p6%22%3A%7B%22p5%22%3A%7B%22len%22%3A10.959615027924276%7D%2C%22p4%22%3A%7B%22len%22%3A14.977745733903651%7D%2C%22p7%22%3A%7B%22len%22%3A17.839596392932567%7D%7D%2C%22p7%22%3A%7B%22p6%22%3A%7B%22len%22%3A17.839596392932567%7D%2C%22p5%22%3A%7B%22len%22%3A11.251003326579944%7D%7D%7D%2C%22extenders%22%3A%7B%22p2%22%3A%7B%22base%22%3A%22p1%22%2C%22ref%22%3A%22p0%22%2C%22angle%22%3A14.44706512820716%2C%22len%22%3A4.919773066101953%2C%22speed%22%3A1%7D%7D%2C%22rotaries%22%3A%7B%22p1%22%3A%22p2%22%7D%2C%22groundPoints%22%3A%7B%22p0%22%3A%7B%22x%22%3A-9.098858770432006%2C%22y%22%3A-3.164757283748611%2C%22id%22%3A%22p0%22%7D%2C%22p1%22%3A%7B%22x%22%3A2.2011412295680053%2C%22y%22%3A-5.364757283748607%2C%22id%22%3A%22p1%22%7D%7D%2C%22solutionMap%22%3A%7B%22p0%22%3A%7B%22p2%22%3A%7B%22p1%22%3A0%2C%22p3%22%3A0%2C%22p5%22%3A1%7D%2C%22p3%22%3A%7B%22p4%22%3A0%7D%2C%22p4%22%3A%7B%22p5%22%3A0%7D%7D%2C%22p2%22%3A%7B%22p0%22%3A%7B%22p1%22%3A1%2C%22p3%22%3A1%2C%22p5%22%3A0%7D%2C%22p4%22%3A%7B%22p5%22%3A0%7D%2C%22p5%22%3A%7B%22p6%22%3A0%7D%7D%2C%22p3%22%3A%7B%22p0%22%3A%7B%22p4%22%3A1%7D%7D%2C%22p4%22%3A%7B%22p2%22%3A%7B%22p5%22%3A1%7D%2C%22p0%22%3A%7B%22p5%22%3A1%7D%2C%22p5%22%3A%7B%22p6%22%3A1%7D%7D%2C%22p5%22%3A%7B%22p2%22%3A%7B%22p6%22%3A1%7D%2C%22p4%22%3A%7B%22p6%22%3A0%7D%2C%22p6%22%3A%7B%22p7%22%3A0%7D%7D%2C%22p6%22%3A%7B%22p5%22%3A%7B%22p7%22%3A1%7D%7D%7D%7D

**Comment by WSPeng** [comment]
> Thanks @WSPeng ! Do you mean the tinyurl.com one? In that case, here's the full URL:
> 
> http://robz.github.io/linkage/?%7B%22points%22%3A%7B%22p0%22%3A%7B%22p1%22%3A%7B%22len%22%3A1%7D%2C%22p3%22%3A%7B%22len%22%3A14.49257629271213%7D%2C%22p4%22%3A%7B%22len%22%3A16.880617054368173%7D%2C%22p5%22%3A%7B%22len%22%3A7.877807259570914%7D%7D%2C%22p1%22%3A%7B%22p0%22%3A%7B%22len%22%3A1%7D%2C%22p2%22%3A%7B%22len%22%3A4.919773066101953%7D%7D%2C%22p2%22%3A%7B%22p1%22%3A%7B%22len%22%3A4.919773066101953%7D%2C%22p3%22%3A%7B%22len%22%3A14.39265093701525%7D%2C%22p5%22%3A%7B%22len%22%3A13.870998062666647%7D%7D%2C%22p3%22%3A%7B%22p0%22%3A%7B%22len%22%3A14.49257629271213%7D%2C%22p2%22%3A%7B%22len%22%3A14.39265093701525%7D%2C%22p4%22%3A%7B%22len%22%3A22.863240340909435%7D%7D%2C%22p4%22%3A%7B%22p0%22%3A%7B%22len%22%3A16.880617054368173%7D%2C%22p3%22%3A%7B%22len%22%3A22.863240340909435%7D%2C%22p6%22%3A%7B%22len%22%3A14.977745733903651%7D%7D%2C%22p5%22%3A%7B%22p0%22%3A%7B%22len%22%3A7.877807259570914%7D%2C%22p2%22%3A%7B%22len%22%3A13.870998062666647%7D%2C%22p6%22%3A%7B%22len%22%3A10.959615027924276%7D%2C%22p7%22%3A%7B%22len%22%3A11.251003326579944%7D%7D%2C%22p6%22%3A%7B%22p5%22%3A%7B%22len%22%3A10.959615027924276%7D%2C%22p4%22%3A%7B%22len%22%3A14.977745733903651%7D%2C%22p7%22%3A%7B%22len%22%3A17.839596392932567%7D%7D%2C%22p7%22%3A%7B%22p6%22%3A%7B%22len%22%3A17.839596392932567%7D%2C%22p5%22%3A%7B%22len%22%3A11.251003326579944%7D%7D%7D%2C%22extenders%22%3A%7B%22p2%22%3A%7B%22base%22%3A%22p1%22%2C%22ref%22%3A%22p0%22%2C%22angle%22%3A14.44706512820716%2C%22len%22%3A4.919773066101953%2C%22speed%22%3A1%7D%7D%2C%22rotaries%22%3A%7B%22p1%22%3A%22p2%22%7D%2C%22groundPoints%22%3A%7B%22p0%22%3A%7B%22x%22%3A-9.098858770432006%2C%22y%22%3A-3.164757283748611%2C%22id%22%3A%22p0%22%7D%2C%22p1%22%3A%7B%22x%22%3A2.2011412295680053%2C%22y%22%3A-5.364757283748607%2C%22id%22%3A%22p1%22%7D%7D%2C%22solutionMap%22%3A%7B%22p0%22%3A%7B%22p2%22%3A%7B%22p1%22%3A0%2C%22p3%22%3A0%2C%22p5%22%3A1%7D%2C%22p3%22%3A%7B%22p4%22%3A0%7D%2C%22p4%22%3A%7B%22p5%22%3A0%7D%7D%2C%22p2%22%3A%7B%22p0%22%3A%7B%22p1%22%3A1%2C%22p3%22%3A1%2C%22p5%22%3A0%7D%2C%22p4%22%3A%7B%22p5%22%3A0%7D%2C%22p5%22%3A%7B%22p6%22%3A0%7D%7D%2C%22p3%22%3A%7B%22p0%22%3A%7B%22p4%22%3A1%7D%7D%2C%22p4%22%3A%7B%22p2%22%3A%7B%22p5%22%3A1%7D%2C%22p0%22%3A%7B%22p5%22%3A1%7D%2C%22p5%22%3A%7B%22p6%22%3A1%7D%7D%2C%22p5%22%3A%7B%22p2%22%3A%7B%22p6%22%3A1%7D%2C%22p4%22%3A%7B%22p6%22%3A0%7D%2C%22p6%22%3A%7B%22p7%22%3A0%7D%7D%2C%22p6%22%3A%7B%22p5%22%3A%7B%22p7%22%3A1%7D%7D%7D%7D

Thank you, it works now.

I am going to close the issue
